config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  resources :users do

       resources :invitations

  end
  namespace :private do
    resources :conversations, only: [:create] do
      member do
        post :close
        post :open
      end
    end
    resources :messages, only: [:index, :create]
  end
  namespace :group do
    resources :conversations do
      member do
        post :close
        post :open
      end
    end
    resources :messages, only: [:index, :create]
  end

  resources :categories
  resources :aposts

   root to: "aposts#index"
  get 'my_friends', to: "users#my_friends"
  get 'my_invitations', to: "invitations#my_invitations"
  get 'myposts', to: "aposts#myposts"
get 'user_posts', to:"aposts#user_posts"
patch 'invitation' ,to: "invitations#update"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

 <%= link_to "Group Site",root_path,class:"navbar-brand" %></li>
    </div> <!-- end div class="navbar-header" -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">  <%= link_to "Posts",root_path,class:"nav-link" %></li>
        <li><%= link_to "Create Posts",new_apost_path,class:"nav-link" %></li>
        <li><%= link_to "My posts",myposts_path,class:"nav-link" %></li>
        <li><%= link_to "Add Category",new_category_path,class:"nav-link" %></li>
        <li><%= link_to "My friends",my_friends_path,class:"nav-link" %></li>
        <li><%= link_to "Add friend",users_path,class:"nav-link" %></li>
        <li><%= link_to "Friend request",my_invitations_path,class:"nav-link" %></li>
      </ul>
      <%= form_tag aposts_path, method: :get,  class:"navbar-form navbar-left" do=%>
        <div class="form-group">
          <%= text_field_tag :search,params[:search],  class:"form-control", placeholder:"Search tittle or a keyword"=%>
        </div>
        <%= submit_tag ("Search"),class:"btn btn-default"=%>
      <%end%>
      <ul class="nav navbar-nav navbar-right">

         <li class="dropdown pc-menu">
        <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span class="caret"></span>
        </a>

        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete,class:"btn btn-danger"  %></li>
        </ul>
      </li>
      </ul>
    </div> <!-- end div class="collapse navbar-collapse" -->
  </div> <!-- end div class="container" -->
</div> <!-- end div class="navbar navbar-default navbar-fixed-top" -->